<template>
  <div class="dashboard">
    <header class="site-header">
      <h1 class="home-link" @click="$router.push('/')">Authly</h1>
      <nav>
        <div class="greeting">
          {{ greetingMessage }}, {{ loggedInUsername }}!
        </div>
        <button class="logout-button" @click="logout">Logout</button>
      </nav>
    </header>

    <div class="main-section">
      <aside class="sidebar">
        <div class="user-info">
          <img class="user-avatar" :src="userAvatar" alt="User Avatar" />
          <h3 class="username">{{ loggedInUsername }}</h3>
          <p class="expires">Expires: {{ expirationDays }} days</p>
          <button class="plan-button">{{ userPlan.toUpperCase() }} PLAN</button>
        </div>

        <ul>
          <li 
              @click="navigate('Licenses')" 
              :class="{ active: currentPage === 'Licenses' }" 
              class="menu-item tab-button"
          >
              <img src="../assets/svg/key-svgrepo-com.svg" alt="Licenses Icon" class="icon" />
              Licenses
          </li>
        </ul>
      </aside>

      <section class="content">
        <transition name="fade-slide">
          <div v-if="currentPage === 'Licenses'" class="licenses-tab">
            <div class="licenses-header">
              <h2 class="licenses-title">Licenses</h2>
              <button class="btn-primary" @click="showCreateLicenseModal = true">Create Licenses</button>
            </div>

            <div class="licenses-panel">
              <table class="licenses-table">
                <thead>
                  <tr>
                    <th>Select</th>
                    <th>Key</th>
                    <th>Creation Date</th>
                    <th>Generated By</th>
                    <th>Duration</th>
                    <th>Type</th>
                    <th>Note</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="license in licenses" :key="license.license_key">
                    <td><input type="checkbox" /></td>
                    <td>{{ license.license_key }}</td>
                    <td>{{ license.creation_date }}</td>
                    <td>{{ license.generated_by }}</td>
                    <td>{{ license.duration }}</td>
                    <td>{{ license.type }}</td>
                    <td>{{ license.note }}</td>
                    <td>{{ license.status }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </transition>

        <div v-if="showCreateLicenseModal" class="modal-overlay">
          <div class="modal">
            <h3>Create Licenses</h3>
            <label>
              License Name:
              <input type="text" v-model="newLicenseName" placeholder="License-5lgj-######" />
            </label>
            <label>
              License Amount:
              <input type="number" v-model="newLicenseAmount" min="1" />
            </label>
            <label>
              License Note:
              <textarea v-model="newLicenseNote" placeholder="Optional note"></textarea>
            </label>
            <label>
              License Type:
              <select v-model="newLicenseType">
                <option value="Day">Day</option>
                <option value="Week">Week</option>
                <option value="Month">Month</option>
                <option value="Year">Year</option>
              </select>
            </label>
            <label>
              License Duration:
              <input type="number" v-model="newLicenseDuration" min="1" />
            </label>
            <div class="modal-actions">
              <button class="btn-primary" @click="createLicenses">Create</button>
              <button class="btn-secondary" @click="showCreateLicenseModal = false">Cancel</button>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

<script>
import CryptoJS from "crypto-js";

export default {
  name: "DashboardPage",
  data() {
    return {
      loggedInUsername: "",
      expirationDays: 0,
      userPlan: "FREE",
      userAvatar: "",
      userSecret: "",
      currentPage: "Licenses",
      licenses: [],
      showCreateLicenseModal: false,
      newLicenseName: "License-5lgj-######",
      newLicenseAmount: 1,
      newLicenseNote: "",
      newLicenseType: "Day",
      newLicenseDuration: 1,
    };
  },
  methods: {
    async fetchUserData(username) {
      try {
        const response = await fetch(`http://localhost:3000/user/${username}`);
        const data = await response.json();
        this.userPlan = data.plan || "FREE";
        this.userAvatar = data.avatar || "default-avatar.png";
        this.userSecret = data.secret;
        const licenseDate = new Date(data.license_date);
        const today = new Date();
        this.expirationDays = Math.max(0, Math.ceil((licenseDate - today) / (1000 * 60 * 60 * 24)));
        this.fetchLicenses();
      } catch (error) {
        alert("Failed to fetch user data");
      }
    },
    async fetchLicenses() {
      try {
        const response = await fetch(`http://localhost:3000/licenses?user_secret=${this.userSecret}`);
        const data = await response.json();
        this.licenses = data;
      } catch (error) {
        alert("Error fetching licenses");
      }
    },
    async createLicenses() {
      if (!this.userSecret) {
        alert("User secret is missing");
        return;
      }

      const licenses = [];
      for (let i = 0; i < this.newLicenseAmount; i++) {
        const randomPart = this.newLicenseName.replace(/#+/g, () =>
          Math.random().toString(36).substring(2, 8).toUpperCase()
        );
        licenses.push({
          user_secret: this.userSecret,
          license_key: randomPart,
          duration: this.newLicenseDuration,
          type: this.newLicenseType,
          note: this.newLicenseNote,
          generated_by: this.loggedInUsername,
        });
      }

      try {
        const response = await fetch('http://localhost:3000/licenses', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ licenses }),
        });
        if (response.ok) {
          alert("Licenses created successfully");
          this.fetchLicenses();
        } else {
          alert("Failed to create licenses");
        }
      } catch (error) {
        alert("An error occurred");
      }

      this.showCreateLicenseModal = false;
    },
    navigate(page) {
      this.currentPage = page;
    },
    logout() {
      localStorage.removeItem("authlyUser");
      alert("Logged out successfully");
      this.$router.push("/login");
    },
  },
  mounted() {
    const storedUser = localStorage.getItem("authlyUser");
    if (storedUser) {
      try {
        const bytes = CryptoJS.AES.decrypt(storedUser, "authly_secret_key");
        const decryptedData = JSON.parse(bytes.toString(CryptoJS.enc.Utf8));
        if (new Date(decryptedData.expiration) > new Date() && decryptedData.username) {
          this.loggedInUsername = decryptedData.username;
          this.fetchUserData(decryptedData.username);
        } else {
          localStorage.removeItem("authlyUser");
          this.$router.push("/login");
        }
      } catch (error) {
        localStorage.removeItem("authlyUser");
        this.$router.push("/login");
      }
    } else {
      this.$router.push("/login");
    }
  },
  computed: {
    greetingMessage() {
      const hour = new Date().getHours();
      if (hour >= 0 && hour < 6) return "Good night";
      if (hour < 12) return "Good morning";
      if (hour < 18) return "Good afternoon";
      return "Good evening";
    },
  },
};
</script>

<style>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}
.modal {
  background: white;
  padding: 20px;
  border-radius: 8px;
  max-width: 500px;
  width: 100%;
}
.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}
</style>

<style src="../assets/dashboard.css"></style>