<template>
  <div class="dashboard">
    <header class="site-header">
      <h1 class="home-link" @click="$router.push('/')">Authly</h1>
      <nav>
        <div class="greeting">
          {{ greetingMessage }}, {{ loggedInUsername }}!
        </div>
        <button class="logout-button" @click="logout">Logout</button>
      </nav>
    </header>

    <div class="main-section">
      <aside class="sidebar">
        <div class="user-info">
          <img class="user-avatar" :src="userAvatar" alt="User Avatar" />
          <h3 class="username">{{ loggedInUsername }}</h3>
          <p class="expires">Expires: {{ expirationDays }} days</p>
          <button class="plan-button">{{ userPlan.toUpperCase() }} PLAN</button>
        </div>

        <ul>
          <li 
              @click="navigate('Licenses')" 
              :class="{ active: currentPage === 'Licenses' }" 
              class="menu-item tab-button"
          >
              <img src="../assets/svg/key-svgrepo-com.svg" alt="Licenses Icon" class="icon" />
              Licenses
          </li>
          <li 
              @click="navigate('Users')" 
              :class="{ active: currentPage === 'Users' }" 
              class="menu-item tab-button"
          >
              <img src="../assets/svg/user-alt-1-svgrepo-com.svg" alt="Users Icon" class="icon" />
              Users
          </li>
          <li 
              @click="navigate('Webhooks')" 
              :class="{ active: currentPage === 'Webhooks' }" 
              class="menu-item tab-button"
          >
              <img src="../assets/svg/figma-svgrepo-com.svg" alt="Webhooks Icon" class="icon" />
              Webhooks
          </li>
          <li 
              @click="navigate('Files')" 
              :class="{ active: currentPage === 'Files' }" 
              class="menu-item tab-button"
          >
              <img src="../assets/svg/files-alt-svgrepo-com.svg" alt="Files Icon" class="icon" />
              Files
          </li>
          <li 
              @click="navigate('settings')" 
              :class="{ active: currentPage === 'settings' }" 
              class="menu-item tab-button"
          >
              <img src="../assets/svg/settings-svgrepo-com.svg" alt="Settings Icon" class="icon" />
              Settings
          </li>
        </ul>
      </aside>

      <section class="content">
        <transition name="fade-slide">
          <component :is="currentPageComponent" v-if="currentPageComponent"></component>
        </transition>
        <transition name="fade-slide">
          <div v-if="!currentPageComponent && currentPage === 'Licenses'" class="licenses-tab">
            <div class="licenses-header">
              <h2 class="licenses-title">Licenses</h2>
            </div>

            <div class="actions">
              <button class="btn-primary">Create Keys</button>
              <button class="btn-secondary">Add Time To Unused Keys</button>
              <button class="btn-primary">Import Keys</button>
              <button class="btn-primary">Export Keys</button>
              <button class="btn-danger">Delete All Keys</button>
              <button class="btn-danger">Delete All Unused Keys</button>
            </div>

            <div class="licenses-panel">
              <table class="licenses-table">
                <thead>
                  <tr>
                    <th>Select</th>
                    <th>Key</th>
                    <th>Creation Date</th>
                    <th>Generated By</th>
                    <th>Duration</th>
                    <th>Note</th>
                    <th>Used On</th>
                    <th>Used By</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="license in licenses" :key="license.key">
                    <td><input type="checkbox" /></td>
                    <td>{{ license.key }}</td>
                    <td>{{ license.creationDate }}</td>
                    <td>{{ license.generatedBy }}</td>
                    <td>{{ license.duration }}</td>
                    <td>{{ license.note }}</td>
                    <td>{{ license.usedOn }}</td>
                    <td>{{ license.usedBy }}</td>
                    <td>{{ license.status }}</td>
                    <td>
                      <button class="btn-action">Actions</button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </transition>
      </section>
    </div>
  </div>
</template>

<script>
import CryptoJS from "crypto-js";

export default {
  name: "DashboardPage",
  data() {
    return {
      loggedInUsername: "User",
      expirationDays: 0,
      userPlan: "FREE",
      userAvatar: "",
      currentPage: "home",
      licenses: [],
    };
  },
  computed: {
    currentPageComponent() {
      return this.currentPage === 'home' || this.currentPage === 'settings' ? this.currentPage : null;
    },
    greetingMessage() {
      const hour = new Date().getHours();
      if (hour >= 0 && hour < 6) return "Good night";
      if (hour < 12) return "Good morning";
      if (hour < 18) return "Good afternoon";
      return "Good evening";
    },
  },
  mounted() {
    const storedUser = localStorage.getItem("authlyUser");
    if (storedUser) {
      try {
        const bytes = CryptoJS.AES.decrypt(storedUser, "authly_secret_key");
        const decryptedData = JSON.parse(bytes.toString(CryptoJS.enc.Utf8));
        if (new Date(decryptedData.expiration) > new Date() && decryptedData.username) {
          this.loggedInUsername = decryptedData.username;
          this.fetchUserData(decryptedData.username);
        } else {
          localStorage.removeItem("authlyUser");
          this.$router.push("/login");
        }
      } catch (error) {
        console.error("Failed to decrypt user data:", error);
        localStorage.removeItem("authlyUser");
        this.$router.push("/login");
      }
    } else {
      this.$router.push("/login");
    }
  },
  methods: {
    async fetchUserData(username) {
      try {
        const response = await fetch(`http://localhost:3000/user/${username}`);
        const data = await response.json();
        this.userPlan = data.plan || "FREE";
        this.userAvatar = data.avatar || "default-avatar.png";
        const licenseDate = new Date(data.license_date);
        const today = new Date();
        this.expirationDays = Math.max(0, Math.ceil((licenseDate - today) / (1000 * 60 * 60 * 24)));
      } catch (error) {
        console.error("Error fetching user data:", error);
        alert("Failed to fetch user data");
      }
    },
    navigate(page) {
      this.currentPage = page;
    },
    logout() {
      localStorage.removeItem("authlyUser");
      alert("Logged out successfully");
      this.$router.push("/login");
    },
  },
};
</script>

<style src="../assets/dashboard.css"></style>